name: Build Electron App

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        env:
          CI: false

      - name: Build the app
        run: npm run make

      - name: List build output
        run: dir out/make

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: discord-app
          path: out/make/*.exe  # Adjust path based on where your .exe is created
