name: Build Electron App

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version you prefer

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build  # Ensure you have a build script in package.json

      - name: Package the app
        run: npm run package  # Ensure you have a package script in package.json

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: discord-app  # Name of the artifact
          path: build/discord-app-*.exe  # Adjust to match your output path and filename pattern
